name: absensi_riverpod
description: "Absensi App with riverpod"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  animated_splash_screen: ^1.3.0
  awesome_dialog: 3.1.0
  cached_network_image: ^3.3.1
  convex_bottom_bar: ^3.2.0
  crypto: ^3.0.3
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_map: ^7.0.2
  flutter_map_location_marker: any
  flutter_riverpod: ^2.5.1
  fluttertoast: ^8.2.6
  fpdart: ^1.1.0
  full_screen_image_null_safe: ^2.0.0
  geolocator: ^12.0.0
  go_router: ^14.2.1
  http: ^1.2.2
  icons_plus: ^5.0.0
  intl: ^0.19.0
  latlong2: ^0.9.1
  pull_to_refresh: ^2.0.0
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0
  ternav_icons: ^1.0.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Black.ttf
        - asset: assets/fonts/Nunito-BlackItalic.ttf
        - asset: assets/fonts/Nunito-Bold.ttf
        - asset: assets/fonts/Nunito-BoldItalic.ttf
        - asset: assets/fonts/Nunito-Italic.ttf
        - asset: assets/fonts/Nunito-Light.ttf
        - asset: assets/fonts/Nunito-LightItalic.ttf
        - asset: assets/fonts/Nunito-Medium.ttf
        - asset: assets/fonts/Nunito-Regular.ttf
  uses-material-design: true
